### ISSUE TITLE
Feedback week 2

### ISSUE THREAD

**Issue by david-vazquez** [XeniaSalinas/mcv-m5#1]
Regarding the overleaf:
 - Write it as a paper, no as a report about a project. Accordingly, do not say things like: "In this project..."
 - Put the github link in a footnote
 - Complete the missing sections

Google Slides:
 - Slide 3 (Intro): too many text
 - These slides are very good to show the work done during this week. However, at the end of the project you will need to have a ppt with ~20 slides of the whole project

Github readme:
 - You should improve it
 - Add list of contributions
 - Add instructions of how to use it
 - ...

Papers summary: Ok

Weights:
 - Perfect

Main repository contributions: 
 - :)

I guess you will get the maximum mark for this week.

Congratulations

**Comment by cristinabustos16** [comment]
Thanks for the feedback
